import type { Metadata } from "next"
import './globals.css'
import { Inter } from "next/font/google"
import AntdRegistry from "./AntdRegistry"
import { ToastContainer } from 'react-toastify'

const inter = Inter({ subsets: ["latin"], variable: "--font-geist-sans" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <AntdRegistry>
          <ToastContainer />
          {children}
        </AntdRegistry>
      </body>
    </html>
  )
}
